
# base image
FROM node:lts-alpine3.18 

# create a dir
WORKDIR /usr/src/app

COPY package.json package-lock.json* tsconfig.json /usr/src/app/

RUN npm install
# copy project to the dir
COPY . /usr/src/app/

# install and build the image
RUN npm run build

EXPOSE 3000

CMD [ "npm" ,"run","start" ]
